Restore Vue 3 `usePage` generic type
inertiajs/inertia pull request #1394
Opened 2023-01-17 05:20 UTC by jessarcher

When converting the adapters to TypeScript, I forgot to copy over the existing type definition for `usePage` which used a generic.

This PR attempts to restore this, however, I can't currently get it to build.

Fixes #1381

2023-01-17 21:26 UTC, hailwood commented
@jessarcher just a note to please check the other adapters too.
I can confirm that the same issue applies to the react adapter.

2023-01-18 03:59 UTC, jessarcher commented
> @jessarcher just a note to please check the other adapters too. I can confirm that the same issue applies to the react adapter.

Good call! Looks like https://github.com/inertiajs/inertia/pull/1396 beat me too it though :)

2023-01-18 04:01 UTC, reinink commented
@innocenzi Hey! We've got this particular issue fixed in #1396, but we're struggling to know exactly how to do this in the Vue adapters. We're getting this error:

```
src/app.ts:119:3 - error TS2322: Type '{ component: string; props: { [x: string]: unknown; errors: Errors & ErrorBag; }; url: string; version: string; scrollRegions: { top: number; left: number; }[]; rememberedState: Record<string, unknown>; resolvedErrors: Errors; }' is not assignable to type 'Page<T>'.
  Types of property 'props' are incompatible.
    Type '{ [x: string]: unknown; errors: Errors & ErrorBag; }' is not assignable to type 'PageProps & T & { errors: Errors & ErrorBag; }'.
      Type '{ [x: string]: unknown; errors: Errors & ErrorBag; }' is not assignable to type 'T'.
        'T' could be instantiated with an arbitrary type which could be unrelated to '{ [x: string]: unknown; errors: Errors & ErrorBag; }'.

119   return page.value
      ~~~~~~~~~~~~~~~~~


Found 1 error in src/app.ts:119
```

Do you have any recommendations on how to fix this?

2023-01-18 08:55 UTC, innocenzi commented
@reinink Looks like the `page` variable is the culprit; it has a generic type of `Page` but the generics are not constrained. I think using `const page = ref<Page<any>>()` would fix it. But I also recommend constraining the generics of `usePage`:

```ts
// in Vue
export function usePage<T extends PageProps>(): Page<T> {
  return page.value
}

// and in core
export interface Page<SharedProps extends PageProps = PageProps> {
  // ...
}
```

2023-01-30 09:51 UTC, Libero-Software commented
Any news on this?

2023-01-30 10:09 UTC, JustInToCoding requested changes

2023-02-02 08:43 UTC, JustInToCoding approved these changes

2023-02-02 23:33 UTC, merged